### ISSUE TITLE
f29 builds

### ISSUE THREAD

**Issue by lsm5** [drahnr/signal-desktop-rpm#2]
First off, thanks for setting this up. Could you please enable builds for f29 as well?

Also, are you looking at getting this officially into Fedora?

**Comment by drahnr** [comment]
Currently I have no plans to make this an official upstream package ( requirements are pretty high as far as I read for splitting things up and I am not a js professional ), I am talking to scott from signal about how to create official rpm packages though.

Currently f29 builds are not working and I'll look into why this is the case either tomorrow or the day after tomorrow (just upgraded today) and a local build is working just fine.

**Comment by drahnr** [comment]
Currently it seems that it is impossible to depend on a certain module for a rpm spec. So until his is fixed, I can not get this published on copr.

**Comment by lsm5** [comment]
By module, do you mean fedora modules (as in the new modularity stuff)?

Could you please post further details about the issue you're seeing?

**Comment by drahnr** [comment]
I created a manual release for the time being https://github.com/drahnr/signal-desktop-rpm/releases/tag/v1.17.2


The spec depends on `nodejs:8` for building, yes the new modularity stuff. As such I would need to specify the dependency on `nodejs <= 8.11.4` in the spec file which does not work (at least `spectool` does not like nor does `rpmbuild -ba`).

**Comment by ghost** [comment]
@drahnr - What's the current situation with these .rpm packages? I am on F29. Tried enabling back my repositories and getting it that way but as per the listed website, the building is broken and I wasn't able to get anything off it. [Here](https://github.com/drahnr/signal-desktop-rpm/releases) I found this _signal-desktop-1.20.0-0.beta.3.fc29.x86_64.rpm_. Does that one work or not? Your _signal-desktop-1.17.2-2.fc29.x86_64.rpm_ takes forever to open up loading messages and seems to be resource-consuming... I decided to uninstall it and try to find an alternative. The aforementioned beta says: `Error: SQLITE_ERROR: no such module: fts5.` Is there any package I could install in order for me to run Signal on my laptop? I assume Signal people haven't done much to add the dependencies unto the source...

**Comment by drahnr** [comment]
I'd label the current state as difficult.

Current builds (`1.20.0` and `1.21.0-beta.3` as of now) are plagued by https://github.com/signalapp/Signal-Desktop/issues/3080 but upstream does not bother too much.

I need modular repostories to build the last working signal version 1.19.0 which can - AFAIK - not be pulled in explicitly as requirement of the rpm spec file.
The same is true for src.rpm, which is why the copr repository can not be updated at this point since the builds always fail.

Ontop of that, fedora modular provides node 8.11.4 where as of signal 1.21.0-beta.3 node 8.12.0 is required.....

So ye, it's fun. I would appreciate some help on the sqlite front.

I'll try to re-trigger v1.19.0 which - now that the release pipeline is in place - should create a release which you can then get at the release page.

**Comment by xai** [comment]
Difficult is a nice description indeed.  
I can't move past v1.19.0 with my own build routine (not using your repo) on f29 as well.  
My hope is that upstream gets more concerned with rpm-based (and modern, see openssl) platforms for future versions as long as we keep the respective issues in the upstream project alive.

**Comment by drahnr** [comment]
So as far as I can see there are two things necessary to get this done:

 * use local node install `node@8.12.0` with `npm`
 * use a sqlcipher fork from https://github.com/drahnr/node-sqlcipher which enables `fts5` without the prelinked so files with crazy rpaths (thanks to @fholzer )

**Comment by drahnr** [comment]
https://github.com/drahnr/signal-desktop-rpm/pull/3 is an attempt but still fails though

**Comment by drahnr** [comment]
1.24.1 released, works, copr still broken though
