### ISSUE TITLE
Packaging signal-desktop

### ISSUE THREAD

**Issue by cryptomilk** [drahnr/signal-desktop-rpm#5]
Hi Bernhard,

I've started to package signal-desktop in the openSUSE Build Service, here:

https://build.opensuse.org/package/show/home:gladiac:signal/signal-desktop

However buildroots don't have internet access to I provide a vendor.tar.xz with the requirements. However this node staff always wants to load something from the web and I'm still trying to prevent this. Especially as long as you download random stuff from the web you will never get a reproducible build.

As soon as I get it working my next step would be to add Fedora. If you're interested we could join our efforts, as I'm using Fedora too.

**Comment by drahnr** [comment]
Hi Andreas,

I would very much like that, especially since lately a lot of library changes cause breakage more often than I'd like.

Tbh, I never considered OBS an option since the amount of manual work to strip out dependencies seemed not feasible given the time available.
I understand the requirement of reproducibility, but my priority was to automate releases to avoid manual work as much as possible.

With fedora the biggest pain is getting the right nodejs version since the minimum required version is below what fedora 30 provides (see the commit history for details).

**Comment by cryptomilk** [comment]
I can't figure out how to do a complete offline build with npm/nodejs

**Comment by drahnr** [comment]
https://negativo17.org/multimedia/ now contains signal-desktop - and its [spec file](https://github.com/negativo17/Signal-Desktop) is significantly shorter / more pristine that I am going to deprecate this and not bother trying to fix js dependencies any longer.
Happy Holidays!
